[project]
name = "physical-ai-humanoid-robotics-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cohere>=5.20.0",
    "qdrant-client>=1.16.2",
    "trafilatura>=2.0.0",
    "types-requests>=2.32.4.20250913",
]
